name: qacart-todo-project

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]   
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          browser: chrome
          record: true
          parallel: true
        env:
          CYPRESS_email: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots